target: model.cldm.TwoStreamControlLDM
params:
  learning_rate: 5e-5

  linear_start: 0.00085
  linear_end: 0.012
  num_timesteps_cond: 1
  log_every_t: 200
  timesteps: 1000
  first_stage_key: "jpg"
  cond_stage_key: "txt"
  control_key: "hint"
  image_size: 64
  channels: 4
  cond_stage_trainable: false
  conditioning_key: crossattn
  monitor: val/loss_simple_ema
  scale_factor: 0.18215
  use_ema: false
  sync_path: /lab/tangb_lab/12132338/BSR/DiffBIR_test/checkpoint/v2-1_512-ema-pruned.ckpt
      #  path to the StableDiffusion v 1.5 weights
  synch_control: false
  ckpt_path_ctr: /lab/tangb_lab/data/stage1_25k.ckpt #/lab/tangb_lab/12132338/BSR/DiffBIR_test/try_twoS_1temb_normal_extratemb/lightning_logs/version_1682/checkpoints/step=24999.ckpt
  control_mode: canny
  control_stage_config:
    target: model.twoStreamControl.TwoStreamControlNet
    params:
      image_size: 32
      in_channels: 4
      out_channels: 4
      hint_channels: 4
      model_channels: 320
      attention_resolutions:
      - 4
      - 2
      - 1
      num_res_blocks: 2
      channel_mult:
      - 1
      - 2
      - 4
      - 4
      num_head_channels: 64
      use_spatial_transformer: true
      use_linear_in_transformer: true
      transformer_depth: 1
      context_dim: 1024
      use_checkpoint: true
      legacy: false
      infusion2control: cat
      infusion2base: add
      guiding: encoder_double
      two_stream_mode: cross
      control_model_ratio: 1
      learn_embedding: true
      fixed: true
  unet_config:
    target: ldm.modules.diffusionmodules.openaimodel.UNetModel
    params:
      image_size: 32
      in_channels: 4
      out_channels: 4
      model_channels: 320
      attention_resolutions:
      - 4
      - 2
      - 1
      num_res_blocks: 2
      channel_mult:
      - 1
      - 2
      - 4
      - 4
      num_head_channels: 64
      use_spatial_transformer: true
      use_linear_in_transformer: True
      transformer_depth: 1
      context_dim: 1024
      use_checkpoint: true
      legacy: false
  first_stage_config:
    target: ldm.models.autoencoder.AutoencoderKL
    params:
      embed_dim: 4
      monitor: val/rec_loss
      ddconfig:
        double_z: true
        z_channels: 4
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
      lossconfig:
        target: torch.nn.Identity

  cond_stage_config:
    target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
    params:
      freeze: True
      layer: "penultimate"

  preprocess_config:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8
