dataset:
  target: dataset.codeformer.CodeformerDataset
  params:
    # Path to the file list.
    file_list: /lab02/tangb_lab/cse12132338/BSR/DiffBIR_test/val.list 
    out_size: 512
    crop_type: none
    use_hflip: False
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 0.2]
    downsample_range: [7, 9]
    noise_range: [0, 1]
    jpeg_range: [90, 100]
    crop_components: False  # facial components
    component_path: ~ 
    eye_enlarge_ratio: 1.4 


data_loader:
  batch_size: 2
  shuffle: false
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
