dataset:
  target: dataset.codeformer.CodeformerDataset
  params:
    # Path to the file list.
    file_list: /lab/tangb_lab/12132338/BSR/DiffBIR_test/train_all.list
    out_size: 512
    crop_type: none
    use_hflip: False
    
    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 10]
    downsample_range: [0.8, 8]
    noise_range: [0, 20]
    jpeg_range: [60, 100]
    #blur_sigma: [0.1, 15]
    #downsample_range: [0.8, 30]
    #noise_range: [0, 20]
    #jpeg_range: [30, 100]
    crop_components: True  # facial components
    component_path: /lab/tangb_lab/12132338/Datasets/NVIDIA-FFHQdataset/FFHQ_eye_mouth_landmarks_512.pth 
    eye_enlarge_ratio: 1.4 

data_loader:
  batch_size: 4
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
